name: CI Build and Test

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  

      - name: Restore dependencies
        run: dotnet restore MarktGuru.Products/MarktGuru.Products.sln

      - name: Build solution
        run: dotnet build MarktGuru.Products/MarktGuru.Products.sln --no-restore --configuration Release

      - name: Run tests
        run: run: dotnet test MarktGuru.Products/MarktGuru.Products.sln --no-build --configuration Release --logger "trx;LogFileName=TestResults.trx" --results-directory MarktGuru.Products/TestResults
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: 'MarktGuru.Products/TestResults/'
